# Generated by Django 6.0.4 on 2026-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.IntegerField(unique=True, verbose_name='Park Yeri Numarası')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Dolu mu?')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
        ),
    ]
