# Generated by Django 6.0.4 on 2026-04-27 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('penalty_points', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ['spot_number']},
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkingspot')),
            ],
        ),
    ]
